select
  profile_id as desired_id,
  ad_id,
  name,
  sex,
  age_min,
  age_max,
  age_mean,
  country_of_residence,
  country_of_origin,
  region,
  village,
  sector_of_activity,
  marital_status,
  number_of_children,
  number_of_children > 0 as has_children,
  illness,
  has_illness,
  qualities,
  values,
  defects,
  interests,
  height_min,
  height_max,
  height_mean,
  weight_min,
  weight_max,
  weight_mean,
  physical_appearance,
  economic,
  education_level,
  relationship_goal,
  created_at
from {{ ref('stg_data__profiles') }}
where profile_type = 'DESIRED'