select
  id as profile_id,
  ad_id,
  profile_type,
  name,
  sex,
  age_min,
  age_max,
  age_mean,
  country_of_residence,
  continent_of_residence,
  country_of_origin,
  continent_of_origin,
  region,
  village,
  sector as sector_of_activity,
  marital_status,
  number_of_children,
  has_children
  illness,
  has_illness,
  qualities,
  values,
  defects,
  interests,
  height_min,
  height_max,
  height_mean,
  weight_min,
  weight_max,
  weight_mean,
  physical_appearance,
  economic,
  education_level,
  relationship_goal,
  created_at
from {{ source('data', 'cleaned_profiles') }}
